name: enhancer-pleiotropy-model
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - numpy=2.2
  - pandas=2.2
  - scipy=1.15
  - pyyaml=6.0
  - pip:
      - pyBigWig>=0.3.22,<0.4
      - snakemake>=8,<10
      - pytest>=8,<10
